[package]
name = "scrabrudo"
version = "0.1.0"
authors = ["Harry Askham <harryaskham@gmail.com>"]
edition = "2018"

[dependencies]
speculate = "0.1.0"
rand = "0.6.1"

[dev-dependencies]
speculate = "0.1.0"
