[package]
name = "scrabrudo"
version = "0.1.0"
authors = ["Harry Askham <harryaskham@gmail.com>"]
edition = "2018"

[dependencies]
speculate = "0.1.0"
rand = "0.6.1"
log = "0.4.6"
cute = "0.3.0"

[dev-dependencies]
speculate = "0.1.0"
